apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 4000  # Service port
      targetPort: 4000  # Container port
  type: ClusterIP  # Use LoadBalancer if you want external access
