apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 2  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: user213-product-service:latest  # Replace with your actual Docker image
          ports:
            - containerPort: 4000
          env:
            - name: DB_HOST
              value: "mongodb-service"  # Update based on your setup
            - name: DB_PORT
              value: "27017"
